#!/bin/tcsh
### Job Name
#PBS -N process_bb
### Charging account
#PBS -AP19010000
### Request one chunk of resources with 1 CPU and 10 GB of memory
#PBS -l select=1:ncpus=1:mem=160GB
### Allow job to run up to 12 hours
#PBS -l walltime=10:45:00
### Route the job to the casper queue
#PBS -q casper
### Join output and error streams into single file
#PBS -o logs/logs.cmip_x.out
#PBS -e logs/err.cmip_x.out


source "/glade/u/apps/opt/conda/etc/profile.d/conda.csh"
conda activate ref


# 2. Open biomass burning emissions
./bb_extract.py




