#!/bin/sh


#path="/glade/derecho/scratch/gaubert/cmip_outputs_2025/f19/model_ready/"
#path="/glade/derecho/scratch/gaubert/cmip_outputs_2025/f19/model_ready/smoothed/"

path="/glade/derecho/scratch/gaubert/cmip_outputs_2025/ne30/model_ready/smoothed/"

#path_out="/glade/derecho/scratch/gaubert/cmip_outputs_2025/f19/model_ready/concat_files/"
#path_out="/glade/derecho/scratch/gaubert/cmip_outputs_2025/f19/model_ready/smoothed/concat_files/"

path_out="/glade/derecho/scratch/gaubert/cmip_outputs_2025/ne30/model_ready/smoothed/concat_files/"



cd ${path}
for files in `ls *_input4MIPs_emissions_CMIP_DRES-CMIP-BB4CMIP7-2-0_gn_175001-189912.nc` ; do
    file_in=${files::-16}
    ls ${file_in}175001-189912.nc ${file_in}190001-202112.nc 
    ncrcat ${file_in}175001-189912.nc ${file_in}190001-202112.nc ${path_out}${file_in}175001-202112.nc


done



exit



